// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backup_prefix.proto

package whatsappbackupreader.protos;

public final class BackupPrefixOuterClass {
  private BackupPrefixOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BackupPrefixOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BackupPrefix)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return Whether the keyType field is set.
     */
    boolean hasKeyType();
    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return The enum numeric value on the wire for keyType.
     */
    int getKeyTypeValue();
    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return The keyType.
     */
    whatsappbackupreader.protos.KeyType.Key_Type getKeyType();

    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     * @return Whether the c14Cipher field is set.
     */
    boolean hasC14Cipher();
    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     * @return The c14Cipher.
     */
    whatsappbackupreader.protos.C14Cipher.C14_cipher getC14Cipher();
    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     */
    whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder getC14CipherOrBuilder();

    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     * @return Whether the c15Iv field is set.
     */
    boolean hasC15Iv();
    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     * @return The c15Iv.
     */
    whatsappbackupreader.protos.C15IV.C15_IV getC15Iv();
    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     */
    whatsappbackupreader.protos.C15IV.C15_IVOrBuilder getC15IvOrBuilder();

    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     * @return Whether the info field is set.
     */
    boolean hasInfo();
    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     * @return The info.
     */
    whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry getInfo();
    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     */
    whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder getInfoOrBuilder();

    public whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.CipherInfoCase getCipherInfoCase();
  }
  /**
   * <pre>
   *This file describes the header you can find near the start of an encrypted backup file.
   * </pre>
   *
   * Protobuf type {@code BackupPrefix}
   */
  public static final class BackupPrefix extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BackupPrefix)
      BackupPrefixOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BackupPrefix.newBuilder() to construct.
    private BackupPrefix(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BackupPrefix() {
      keyType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BackupPrefix();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BackupPrefix(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              bitField0_ |= 0x00000001;
              keyType_ = rawValue;
              break;
            }
            case 18: {
              whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder subBuilder = null;
              if (cipherInfoCase_ == 2) {
                subBuilder = ((whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_).toBuilder();
              }
              cipherInfo_ =
                  input.readMessage(whatsappbackupreader.protos.C14Cipher.C14_cipher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_);
                cipherInfo_ = subBuilder.buildPartial();
              }
              cipherInfoCase_ = 2;
              break;
            }
            case 26: {
              whatsappbackupreader.protos.C15IV.C15_IV.Builder subBuilder = null;
              if (cipherInfoCase_ == 3) {
                subBuilder = ((whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_).toBuilder();
              }
              cipherInfo_ =
                  input.readMessage(whatsappbackupreader.protos.C15IV.C15_IV.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_);
                cipherInfo_ = subBuilder.buildPartial();
              }
              cipherInfoCase_ = 3;
              break;
            }
            case 34: {
              whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return whatsappbackupreader.protos.BackupPrefixOuterClass.internal_static_BackupPrefix_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return whatsappbackupreader.protos.BackupPrefixOuterClass.internal_static_BackupPrefix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.class, whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.Builder.class);
    }

    private int bitField0_;
    private int cipherInfoCase_ = 0;
    private java.lang.Object cipherInfo_;
    public enum CipherInfoCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      C14_CIPHER(2),
      C15_IV(3),
      CIPHERINFO_NOT_SET(0);
      private final int value;
      private CipherInfoCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CipherInfoCase valueOf(int value) {
        return forNumber(value);
      }

      public static CipherInfoCase forNumber(int value) {
        switch (value) {
          case 2: return C14_CIPHER;
          case 3: return C15_IV;
          case 0: return CIPHERINFO_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CipherInfoCase
    getCipherInfoCase() {
      return CipherInfoCase.forNumber(
          cipherInfoCase_);
    }

    public static final int KEY_TYPE_FIELD_NUMBER = 1;
    private int keyType_;
    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return Whether the keyType field is set.
     */
    @java.lang.Override public boolean hasKeyType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return The enum numeric value on the wire for keyType.
     */
    @java.lang.Override public int getKeyTypeValue() {
      return keyType_;
    }
    /**
     * <pre>
     * The "optional" here is to make protobuf serialize the zero as well,
     * otherwise, being the default for numeric, it would be omitted.
     * </pre>
     *
     * <code>.Key_Type key_type = 1;</code>
     * @return The keyType.
     */
    @java.lang.Override public whatsappbackupreader.protos.KeyType.Key_Type getKeyType() {
      @SuppressWarnings("deprecation")
      whatsappbackupreader.protos.KeyType.Key_Type result = whatsappbackupreader.protos.KeyType.Key_Type.valueOf(keyType_);
      return result == null ? whatsappbackupreader.protos.KeyType.Key_Type.UNRECOGNIZED : result;
    }

    public static final int C14_CIPHER_FIELD_NUMBER = 2;
    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     * @return Whether the c14Cipher field is set.
     */
    @java.lang.Override
    public boolean hasC14Cipher() {
      return cipherInfoCase_ == 2;
    }
    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     * @return The c14Cipher.
     */
    @java.lang.Override
    public whatsappbackupreader.protos.C14Cipher.C14_cipher getC14Cipher() {
      if (cipherInfoCase_ == 2) {
         return (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_;
      }
      return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
    }
    /**
     * <pre>
     * If DB is crypt14
     * </pre>
     *
     * <code>.C14_cipher c14_cipher = 2;</code>
     */
    @java.lang.Override
    public whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder getC14CipherOrBuilder() {
      if (cipherInfoCase_ == 2) {
         return (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_;
      }
      return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
    }

    public static final int C15_IV_FIELD_NUMBER = 3;
    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     * @return Whether the c15Iv field is set.
     */
    @java.lang.Override
    public boolean hasC15Iv() {
      return cipherInfoCase_ == 3;
    }
    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     * @return The c15Iv.
     */
    @java.lang.Override
    public whatsappbackupreader.protos.C15IV.C15_IV getC15Iv() {
      if (cipherInfoCase_ == 3) {
         return (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_;
      }
      return whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
    }
    /**
     * <pre>
     * If DB is crypt15
     * </pre>
     *
     * <code>.C15_IV c15_iv = 3;</code>
     */
    @java.lang.Override
    public whatsappbackupreader.protos.C15IV.C15_IVOrBuilder getC15IvOrBuilder() {
      if (cipherInfoCase_ == 3) {
         return (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_;
      }
      return whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
    }

    public static final int INFO_FIELD_NUMBER = 4;
    private whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry info_;
    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     * @return Whether the info field is set.
     */
    @java.lang.Override
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     * @return The info.
     */
    @java.lang.Override
    public whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry getInfo() {
      return info_ == null ? whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.getDefaultInstance() : info_;
    }
    /**
     * <pre>
     * Version that generated backup and other infos
     * </pre>
     *
     * <code>.BackupExpiry info = 4;</code>
     */
    @java.lang.Override
    public whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, keyType_);
      }
      if (cipherInfoCase_ == 2) {
        output.writeMessage(2, (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_);
      }
      if (cipherInfoCase_ == 3) {
        output.writeMessage(3, (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_);
      }
      if (info_ != null) {
        output.writeMessage(4, getInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, keyType_);
      }
      if (cipherInfoCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_);
      }
      if (cipherInfoCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_);
      }
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix)) {
        return super.equals(obj);
      }
      whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix other = (whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix) obj;

      if (hasKeyType() != other.hasKeyType()) return false;
      if (hasKeyType()) {
        if (keyType_ != other.keyType_) return false;
      }
      if (hasInfo() != other.hasInfo()) return false;
      if (hasInfo()) {
        if (!getInfo()
            .equals(other.getInfo())) return false;
      }
      if (!getCipherInfoCase().equals(other.getCipherInfoCase())) return false;
      switch (cipherInfoCase_) {
        case 2:
          if (!getC14Cipher()
              .equals(other.getC14Cipher())) return false;
          break;
        case 3:
          if (!getC15Iv()
              .equals(other.getC15Iv())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKeyType()) {
        hash = (37 * hash) + KEY_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + keyType_;
      }
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      switch (cipherInfoCase_) {
        case 2:
          hash = (37 * hash) + C14_CIPHER_FIELD_NUMBER;
          hash = (53 * hash) + getC14Cipher().hashCode();
          break;
        case 3:
          hash = (37 * hash) + C15_IV_FIELD_NUMBER;
          hash = (53 * hash) + getC15Iv().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *This file describes the header you can find near the start of an encrypted backup file.
     * </pre>
     *
     * Protobuf type {@code BackupPrefix}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BackupPrefix)
        whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefixOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return whatsappbackupreader.protos.BackupPrefixOuterClass.internal_static_BackupPrefix_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return whatsappbackupreader.protos.BackupPrefixOuterClass.internal_static_BackupPrefix_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.class, whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.Builder.class);
      }

      // Construct using whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        cipherInfoCase_ = 0;
        cipherInfo_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return whatsappbackupreader.protos.BackupPrefixOuterClass.internal_static_BackupPrefix_descriptor;
      }

      @java.lang.Override
      public whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix getDefaultInstanceForType() {
        return whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.getDefaultInstance();
      }

      @java.lang.Override
      public whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix build() {
        whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix buildPartial() {
        whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix result = new whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyType_ = keyType_;
        if (cipherInfoCase_ == 2) {
          if (c14CipherBuilder_ == null) {
            result.cipherInfo_ = cipherInfo_;
          } else {
            result.cipherInfo_ = c14CipherBuilder_.build();
          }
        }
        if (cipherInfoCase_ == 3) {
          if (c15IvBuilder_ == null) {
            result.cipherInfo_ = cipherInfo_;
          } else {
            result.cipherInfo_ = c15IvBuilder_.build();
          }
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        result.cipherInfoCase_ = cipherInfoCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix) {
          return mergeFrom((whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix other) {
        if (other == whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix.getDefaultInstance()) return this;
        if (other.hasKeyType()) {
          setKeyType(other.getKeyType());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        switch (other.getCipherInfoCase()) {
          case C14_CIPHER: {
            mergeC14Cipher(other.getC14Cipher());
            break;
          }
          case C15_IV: {
            mergeC15Iv(other.getC15Iv());
            break;
          }
          case CIPHERINFO_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cipherInfoCase_ = 0;
      private java.lang.Object cipherInfo_;
      public CipherInfoCase
          getCipherInfoCase() {
        return CipherInfoCase.forNumber(
            cipherInfoCase_);
      }

      public Builder clearCipherInfo() {
        cipherInfoCase_ = 0;
        cipherInfo_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int keyType_ = 0;
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @return Whether the keyType field is set.
       */
      @java.lang.Override public boolean hasKeyType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @return The enum numeric value on the wire for keyType.
       */
      @java.lang.Override public int getKeyTypeValue() {
        return keyType_;
      }
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @param value The enum numeric value on the wire for keyType to set.
       * @return This builder for chaining.
       */
      public Builder setKeyTypeValue(int value) {
        bitField0_ |= 0x00000001;
        keyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @return The keyType.
       */
      @java.lang.Override
      public whatsappbackupreader.protos.KeyType.Key_Type getKeyType() {
        @SuppressWarnings("deprecation")
        whatsappbackupreader.protos.KeyType.Key_Type result = whatsappbackupreader.protos.KeyType.Key_Type.valueOf(keyType_);
        return result == null ? whatsappbackupreader.protos.KeyType.Key_Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @param value The keyType to set.
       * @return This builder for chaining.
       */
      public Builder setKeyType(whatsappbackupreader.protos.KeyType.Key_Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        keyType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The "optional" here is to make protobuf serialize the zero as well,
       * otherwise, being the default for numeric, it would be omitted.
       * </pre>
       *
       * <code>.Key_Type key_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.C14Cipher.C14_cipher, whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder, whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder> c14CipherBuilder_;
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       * @return Whether the c14Cipher field is set.
       */
      @java.lang.Override
      public boolean hasC14Cipher() {
        return cipherInfoCase_ == 2;
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       * @return The c14Cipher.
       */
      @java.lang.Override
      public whatsappbackupreader.protos.C14Cipher.C14_cipher getC14Cipher() {
        if (c14CipherBuilder_ == null) {
          if (cipherInfoCase_ == 2) {
            return (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_;
          }
          return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
        } else {
          if (cipherInfoCase_ == 2) {
            return c14CipherBuilder_.getMessage();
          }
          return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      public Builder setC14Cipher(whatsappbackupreader.protos.C14Cipher.C14_cipher value) {
        if (c14CipherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cipherInfo_ = value;
          onChanged();
        } else {
          c14CipherBuilder_.setMessage(value);
        }
        cipherInfoCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      public Builder setC14Cipher(
          whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder builderForValue) {
        if (c14CipherBuilder_ == null) {
          cipherInfo_ = builderForValue.build();
          onChanged();
        } else {
          c14CipherBuilder_.setMessage(builderForValue.build());
        }
        cipherInfoCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      public Builder mergeC14Cipher(whatsappbackupreader.protos.C14Cipher.C14_cipher value) {
        if (c14CipherBuilder_ == null) {
          if (cipherInfoCase_ == 2 &&
              cipherInfo_ != whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance()) {
            cipherInfo_ = whatsappbackupreader.protos.C14Cipher.C14_cipher.newBuilder((whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_)
                .mergeFrom(value).buildPartial();
          } else {
            cipherInfo_ = value;
          }
          onChanged();
        } else {
          if (cipherInfoCase_ == 2) {
            c14CipherBuilder_.mergeFrom(value);
          }
          c14CipherBuilder_.setMessage(value);
        }
        cipherInfoCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      public Builder clearC14Cipher() {
        if (c14CipherBuilder_ == null) {
          if (cipherInfoCase_ == 2) {
            cipherInfoCase_ = 0;
            cipherInfo_ = null;
            onChanged();
          }
        } else {
          if (cipherInfoCase_ == 2) {
            cipherInfoCase_ = 0;
            cipherInfo_ = null;
          }
          c14CipherBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      public whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder getC14CipherBuilder() {
        return getC14CipherFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      @java.lang.Override
      public whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder getC14CipherOrBuilder() {
        if ((cipherInfoCase_ == 2) && (c14CipherBuilder_ != null)) {
          return c14CipherBuilder_.getMessageOrBuilder();
        } else {
          if (cipherInfoCase_ == 2) {
            return (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_;
          }
          return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * If DB is crypt14
       * </pre>
       *
       * <code>.C14_cipher c14_cipher = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.C14Cipher.C14_cipher, whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder, whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder> 
          getC14CipherFieldBuilder() {
        if (c14CipherBuilder_ == null) {
          if (!(cipherInfoCase_ == 2)) {
            cipherInfo_ = whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
          }
          c14CipherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              whatsappbackupreader.protos.C14Cipher.C14_cipher, whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder, whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder>(
                  (whatsappbackupreader.protos.C14Cipher.C14_cipher) cipherInfo_,
                  getParentForChildren(),
                  isClean());
          cipherInfo_ = null;
        }
        cipherInfoCase_ = 2;
        onChanged();;
        return c14CipherBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.C15IV.C15_IV, whatsappbackupreader.protos.C15IV.C15_IV.Builder, whatsappbackupreader.protos.C15IV.C15_IVOrBuilder> c15IvBuilder_;
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       * @return Whether the c15Iv field is set.
       */
      @java.lang.Override
      public boolean hasC15Iv() {
        return cipherInfoCase_ == 3;
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       * @return The c15Iv.
       */
      @java.lang.Override
      public whatsappbackupreader.protos.C15IV.C15_IV getC15Iv() {
        if (c15IvBuilder_ == null) {
          if (cipherInfoCase_ == 3) {
            return (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_;
          }
          return whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
        } else {
          if (cipherInfoCase_ == 3) {
            return c15IvBuilder_.getMessage();
          }
          return whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      public Builder setC15Iv(whatsappbackupreader.protos.C15IV.C15_IV value) {
        if (c15IvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cipherInfo_ = value;
          onChanged();
        } else {
          c15IvBuilder_.setMessage(value);
        }
        cipherInfoCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      public Builder setC15Iv(
          whatsappbackupreader.protos.C15IV.C15_IV.Builder builderForValue) {
        if (c15IvBuilder_ == null) {
          cipherInfo_ = builderForValue.build();
          onChanged();
        } else {
          c15IvBuilder_.setMessage(builderForValue.build());
        }
        cipherInfoCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      public Builder mergeC15Iv(whatsappbackupreader.protos.C15IV.C15_IV value) {
        if (c15IvBuilder_ == null) {
          if (cipherInfoCase_ == 3 &&
              cipherInfo_ != whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance()) {
            cipherInfo_ = whatsappbackupreader.protos.C15IV.C15_IV.newBuilder((whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_)
                .mergeFrom(value).buildPartial();
          } else {
            cipherInfo_ = value;
          }
          onChanged();
        } else {
          if (cipherInfoCase_ == 3) {
            c15IvBuilder_.mergeFrom(value);
          }
          c15IvBuilder_.setMessage(value);
        }
        cipherInfoCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      public Builder clearC15Iv() {
        if (c15IvBuilder_ == null) {
          if (cipherInfoCase_ == 3) {
            cipherInfoCase_ = 0;
            cipherInfo_ = null;
            onChanged();
          }
        } else {
          if (cipherInfoCase_ == 3) {
            cipherInfoCase_ = 0;
            cipherInfo_ = null;
          }
          c15IvBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      public whatsappbackupreader.protos.C15IV.C15_IV.Builder getC15IvBuilder() {
        return getC15IvFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      @java.lang.Override
      public whatsappbackupreader.protos.C15IV.C15_IVOrBuilder getC15IvOrBuilder() {
        if ((cipherInfoCase_ == 3) && (c15IvBuilder_ != null)) {
          return c15IvBuilder_.getMessageOrBuilder();
        } else {
          if (cipherInfoCase_ == 3) {
            return (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_;
          }
          return whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * If DB is crypt15
       * </pre>
       *
       * <code>.C15_IV c15_iv = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.C15IV.C15_IV, whatsappbackupreader.protos.C15IV.C15_IV.Builder, whatsappbackupreader.protos.C15IV.C15_IVOrBuilder> 
          getC15IvFieldBuilder() {
        if (c15IvBuilder_ == null) {
          if (!(cipherInfoCase_ == 3)) {
            cipherInfo_ = whatsappbackupreader.protos.C15IV.C15_IV.getDefaultInstance();
          }
          c15IvBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              whatsappbackupreader.protos.C15IV.C15_IV, whatsappbackupreader.protos.C15IV.C15_IV.Builder, whatsappbackupreader.protos.C15IV.C15_IVOrBuilder>(
                  (whatsappbackupreader.protos.C15IV.C15_IV) cipherInfo_,
                  getParentForChildren(),
                  isClean());
          cipherInfo_ = null;
        }
        cipherInfoCase_ = 3;
        onChanged();;
        return c15IvBuilder_;
      }

      private whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry info_;
      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder> infoBuilder_;
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       * @return Whether the info field is set.
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       * @return The info.
       */
      public whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public Builder setInfo(whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public Builder setInfo(
          whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public Builder mergeInfo(whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder getInfoBuilder() {
        
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      public whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.getDefaultInstance() : info_;
        }
      }
      /**
       * <pre>
       * Version that generated backup and other infos
       * </pre>
       *
       * <code>.BackupExpiry info = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiry.Builder, whatsappbackupreader.protos.BackupExpiryOuterClass.BackupExpiryOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BackupPrefix)
    }

    // @@protoc_insertion_point(class_scope:BackupPrefix)
    private static final whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix();
    }

    public static whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BackupPrefix>
        PARSER = new com.google.protobuf.AbstractParser<BackupPrefix>() {
      @java.lang.Override
      public BackupPrefix parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BackupPrefix(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BackupPrefix> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BackupPrefix> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public whatsappbackupreader.protos.BackupPrefixOuterClass.BackupPrefix getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BackupPrefix_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BackupPrefix_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023backup_prefix.proto\032\020C14_cipher.proto\032" +
      "\014C15_IV.proto\032\016key_type.proto\032\023backup_ex" +
      "piry.proto\"\247\001\n\014BackupPrefix\022 \n\010key_type\030" +
      "\001 \001(\0162\t.Key_TypeH\001\210\001\001\022!\n\nc14_cipher\030\002 \001(" +
      "\0132\013.C14_cipherH\000\022\031\n\006c15_iv\030\003 \001(\0132\007.C15_I" +
      "VH\000\022\033\n\004info\030\004 \001(\0132\r.BackupExpiryB\r\n\013ciph" +
      "er_infoB\013\n\t_key_typeB\035\n\033whatsappbackupre" +
      "ader.protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          whatsappbackupreader.protos.C14Cipher.getDescriptor(),
          whatsappbackupreader.protos.C15IV.getDescriptor(),
          whatsappbackupreader.protos.KeyType.getDescriptor(),
          whatsappbackupreader.protos.BackupExpiryOuterClass.getDescriptor(),
        });
    internal_static_BackupPrefix_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BackupPrefix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BackupPrefix_descriptor,
        new java.lang.String[] { "KeyType", "C14Cipher", "C15Iv", "Info", "CipherInfo", "KeyType", });
    whatsappbackupreader.protos.C14Cipher.getDescriptor();
    whatsappbackupreader.protos.C15IV.getDescriptor();
    whatsappbackupreader.protos.KeyType.getDescriptor();
    whatsappbackupreader.protos.BackupExpiryOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
