// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C14_cipher.proto

package whatsappbackupreader.protos;

public final class C14Cipher {
  private C14Cipher() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C14_cipherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C14_cipher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * is usually 0001
     * </pre>
     *
     * <code>bytes cipher_version = 1;</code>
     * @return The cipherVersion.
     */
    com.google.protobuf.ByteString getCipherVersion();

    /**
     * <pre>
     * Is usually "1"
     * </pre>
     *
     * <code>bytes key_version = 2;</code>
     * @return The keyVersion.
     */
    com.google.protobuf.ByteString getKeyVersion();

    /**
     * <pre>
     * The 32-bytes long server salt
     * </pre>
     *
     * <code>bytes server_salt = 3;</code>
     * @return The serverSalt.
     */
    com.google.protobuf.ByteString getServerSalt();

    /**
     * <pre>
     * The 16-bytes long google id salt
     * </pre>
     *
     * <code>bytes google_id = 4;</code>
     * @return The googleId.
     */
    com.google.protobuf.ByteString getGoogleId();

    /**
     * <pre>
     * The 16-bytes long IV
     * </pre>
     *
     * <code>bytes IV = 5;</code>
     * @return The iV.
     */
    com.google.protobuf.ByteString getIV();
  }
  /**
   * <pre>
   * crypt14 cipher files.
   * </pre>
   *
   * Protobuf type {@code C14_cipher}
   */
  public static final class C14_cipher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C14_cipher)
      C14_cipherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C14_cipher.newBuilder() to construct.
    private C14_cipher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C14_cipher() {
      cipherVersion_ = com.google.protobuf.ByteString.EMPTY;
      keyVersion_ = com.google.protobuf.ByteString.EMPTY;
      serverSalt_ = com.google.protobuf.ByteString.EMPTY;
      googleId_ = com.google.protobuf.ByteString.EMPTY;
      iV_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C14_cipher();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C14_cipher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              cipherVersion_ = input.readBytes();
              break;
            }
            case 18: {

              keyVersion_ = input.readBytes();
              break;
            }
            case 26: {

              serverSalt_ = input.readBytes();
              break;
            }
            case 34: {

              googleId_ = input.readBytes();
              break;
            }
            case 42: {

              iV_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return whatsappbackupreader.protos.C14Cipher.internal_static_C14_cipher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return whatsappbackupreader.protos.C14Cipher.internal_static_C14_cipher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              whatsappbackupreader.protos.C14Cipher.C14_cipher.class, whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder.class);
    }

    public static final int CIPHER_VERSION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString cipherVersion_;
    /**
     * <pre>
     * is usually 0001
     * </pre>
     *
     * <code>bytes cipher_version = 1;</code>
     * @return The cipherVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCipherVersion() {
      return cipherVersion_;
    }

    public static final int KEY_VERSION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString keyVersion_;
    /**
     * <pre>
     * Is usually "1"
     * </pre>
     *
     * <code>bytes key_version = 2;</code>
     * @return The keyVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKeyVersion() {
      return keyVersion_;
    }

    public static final int SERVER_SALT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString serverSalt_;
    /**
     * <pre>
     * The 32-bytes long server salt
     * </pre>
     *
     * <code>bytes server_salt = 3;</code>
     * @return The serverSalt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getServerSalt() {
      return serverSalt_;
    }

    public static final int GOOGLE_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString googleId_;
    /**
     * <pre>
     * The 16-bytes long google id salt
     * </pre>
     *
     * <code>bytes google_id = 4;</code>
     * @return The googleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGoogleId() {
      return googleId_;
    }

    public static final int IV_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString iV_;
    /**
     * <pre>
     * The 16-bytes long IV
     * </pre>
     *
     * <code>bytes IV = 5;</code>
     * @return The iV.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIV() {
      return iV_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!cipherVersion_.isEmpty()) {
        output.writeBytes(1, cipherVersion_);
      }
      if (!keyVersion_.isEmpty()) {
        output.writeBytes(2, keyVersion_);
      }
      if (!serverSalt_.isEmpty()) {
        output.writeBytes(3, serverSalt_);
      }
      if (!googleId_.isEmpty()) {
        output.writeBytes(4, googleId_);
      }
      if (!iV_.isEmpty()) {
        output.writeBytes(5, iV_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!cipherVersion_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, cipherVersion_);
      }
      if (!keyVersion_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, keyVersion_);
      }
      if (!serverSalt_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, serverSalt_);
      }
      if (!googleId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, googleId_);
      }
      if (!iV_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, iV_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof whatsappbackupreader.protos.C14Cipher.C14_cipher)) {
        return super.equals(obj);
      }
      whatsappbackupreader.protos.C14Cipher.C14_cipher other = (whatsappbackupreader.protos.C14Cipher.C14_cipher) obj;

      if (!getCipherVersion()
          .equals(other.getCipherVersion())) return false;
      if (!getKeyVersion()
          .equals(other.getKeyVersion())) return false;
      if (!getServerSalt()
          .equals(other.getServerSalt())) return false;
      if (!getGoogleId()
          .equals(other.getGoogleId())) return false;
      if (!getIV()
          .equals(other.getIV())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CIPHER_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCipherVersion().hashCode();
      hash = (37 * hash) + KEY_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getKeyVersion().hashCode();
      hash = (37 * hash) + SERVER_SALT_FIELD_NUMBER;
      hash = (53 * hash) + getServerSalt().hashCode();
      hash = (37 * hash) + GOOGLE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGoogleId().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIV().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static whatsappbackupreader.protos.C14Cipher.C14_cipher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(whatsappbackupreader.protos.C14Cipher.C14_cipher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * crypt14 cipher files.
     * </pre>
     *
     * Protobuf type {@code C14_cipher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C14_cipher)
        whatsappbackupreader.protos.C14Cipher.C14_cipherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return whatsappbackupreader.protos.C14Cipher.internal_static_C14_cipher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return whatsappbackupreader.protos.C14Cipher.internal_static_C14_cipher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                whatsappbackupreader.protos.C14Cipher.C14_cipher.class, whatsappbackupreader.protos.C14Cipher.C14_cipher.Builder.class);
      }

      // Construct using whatsappbackupreader.protos.C14Cipher.C14_cipher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cipherVersion_ = com.google.protobuf.ByteString.EMPTY;

        keyVersion_ = com.google.protobuf.ByteString.EMPTY;

        serverSalt_ = com.google.protobuf.ByteString.EMPTY;

        googleId_ = com.google.protobuf.ByteString.EMPTY;

        iV_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return whatsappbackupreader.protos.C14Cipher.internal_static_C14_cipher_descriptor;
      }

      @java.lang.Override
      public whatsappbackupreader.protos.C14Cipher.C14_cipher getDefaultInstanceForType() {
        return whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance();
      }

      @java.lang.Override
      public whatsappbackupreader.protos.C14Cipher.C14_cipher build() {
        whatsappbackupreader.protos.C14Cipher.C14_cipher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public whatsappbackupreader.protos.C14Cipher.C14_cipher buildPartial() {
        whatsappbackupreader.protos.C14Cipher.C14_cipher result = new whatsappbackupreader.protos.C14Cipher.C14_cipher(this);
        result.cipherVersion_ = cipherVersion_;
        result.keyVersion_ = keyVersion_;
        result.serverSalt_ = serverSalt_;
        result.googleId_ = googleId_;
        result.iV_ = iV_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof whatsappbackupreader.protos.C14Cipher.C14_cipher) {
          return mergeFrom((whatsappbackupreader.protos.C14Cipher.C14_cipher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(whatsappbackupreader.protos.C14Cipher.C14_cipher other) {
        if (other == whatsappbackupreader.protos.C14Cipher.C14_cipher.getDefaultInstance()) return this;
        if (other.getCipherVersion() != com.google.protobuf.ByteString.EMPTY) {
          setCipherVersion(other.getCipherVersion());
        }
        if (other.getKeyVersion() != com.google.protobuf.ByteString.EMPTY) {
          setKeyVersion(other.getKeyVersion());
        }
        if (other.getServerSalt() != com.google.protobuf.ByteString.EMPTY) {
          setServerSalt(other.getServerSalt());
        }
        if (other.getGoogleId() != com.google.protobuf.ByteString.EMPTY) {
          setGoogleId(other.getGoogleId());
        }
        if (other.getIV() != com.google.protobuf.ByteString.EMPTY) {
          setIV(other.getIV());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        whatsappbackupreader.protos.C14Cipher.C14_cipher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (whatsappbackupreader.protos.C14Cipher.C14_cipher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString cipherVersion_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * is usually 0001
       * </pre>
       *
       * <code>bytes cipher_version = 1;</code>
       * @return The cipherVersion.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCipherVersion() {
        return cipherVersion_;
      }
      /**
       * <pre>
       * is usually 0001
       * </pre>
       *
       * <code>bytes cipher_version = 1;</code>
       * @param value The cipherVersion to set.
       * @return This builder for chaining.
       */
      public Builder setCipherVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cipherVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * is usually 0001
       * </pre>
       *
       * <code>bytes cipher_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCipherVersion() {
        
        cipherVersion_ = getDefaultInstance().getCipherVersion();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString keyVersion_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Is usually "1"
       * </pre>
       *
       * <code>bytes key_version = 2;</code>
       * @return The keyVersion.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKeyVersion() {
        return keyVersion_;
      }
      /**
       * <pre>
       * Is usually "1"
       * </pre>
       *
       * <code>bytes key_version = 2;</code>
       * @param value The keyVersion to set.
       * @return This builder for chaining.
       */
      public Builder setKeyVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Is usually "1"
       * </pre>
       *
       * <code>bytes key_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyVersion() {
        
        keyVersion_ = getDefaultInstance().getKeyVersion();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString serverSalt_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The 32-bytes long server salt
       * </pre>
       *
       * <code>bytes server_salt = 3;</code>
       * @return The serverSalt.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getServerSalt() {
        return serverSalt_;
      }
      /**
       * <pre>
       * The 32-bytes long server salt
       * </pre>
       *
       * <code>bytes server_salt = 3;</code>
       * @param value The serverSalt to set.
       * @return This builder for chaining.
       */
      public Builder setServerSalt(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverSalt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The 32-bytes long server salt
       * </pre>
       *
       * <code>bytes server_salt = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerSalt() {
        
        serverSalt_ = getDefaultInstance().getServerSalt();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString googleId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The 16-bytes long google id salt
       * </pre>
       *
       * <code>bytes google_id = 4;</code>
       * @return The googleId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGoogleId() {
        return googleId_;
      }
      /**
       * <pre>
       * The 16-bytes long google id salt
       * </pre>
       *
       * <code>bytes google_id = 4;</code>
       * @param value The googleId to set.
       * @return This builder for chaining.
       */
      public Builder setGoogleId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        googleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The 16-bytes long google id salt
       * </pre>
       *
       * <code>bytes google_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoogleId() {
        
        googleId_ = getDefaultInstance().getGoogleId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iV_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The 16-bytes long IV
       * </pre>
       *
       * <code>bytes IV = 5;</code>
       * @return The iV.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIV() {
        return iV_;
      }
      /**
       * <pre>
       * The 16-bytes long IV
       * </pre>
       *
       * <code>bytes IV = 5;</code>
       * @param value The iV to set.
       * @return This builder for chaining.
       */
      public Builder setIV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iV_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The 16-bytes long IV
       * </pre>
       *
       * <code>bytes IV = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIV() {
        
        iV_ = getDefaultInstance().getIV();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C14_cipher)
    }

    // @@protoc_insertion_point(class_scope:C14_cipher)
    private static final whatsappbackupreader.protos.C14Cipher.C14_cipher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new whatsappbackupreader.protos.C14Cipher.C14_cipher();
    }

    public static whatsappbackupreader.protos.C14Cipher.C14_cipher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C14_cipher>
        PARSER = new com.google.protobuf.AbstractParser<C14_cipher>() {
      @java.lang.Override
      public C14_cipher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C14_cipher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C14_cipher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C14_cipher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public whatsappbackupreader.protos.C14Cipher.C14_cipher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C14_cipher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C14_cipher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020C14_cipher.proto\"m\n\nC14_cipher\022\026\n\016ciph" +
      "er_version\030\001 \001(\014\022\023\n\013key_version\030\002 \001(\014\022\023\n" +
      "\013server_salt\030\003 \001(\014\022\021\n\tgoogle_id\030\004 \001(\014\022\n\n" +
      "\002IV\030\005 \001(\014B\035\n\033whatsappbackupreader.protos" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_C14_cipher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C14_cipher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C14_cipher_descriptor,
        new java.lang.String[] { "CipherVersion", "KeyVersion", "ServerSalt", "GoogleId", "IV", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
