// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_type.proto

package whatsappbackupreader.protos;

public final class KeyType {
  private KeyType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * This enum describes if the key is self-managed by WhatsApp of if it is stored in the HSM.
   * In other words, traditional = 0, end-to-end = 1
   * </pre>
   *
   * Protobuf enum {@code Key_Type}
   */
  public enum Key_Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WA_PROVIDED = 0;</code>
     */
    WA_PROVIDED(0),
    /**
     * <code>HSM_CONTROLLED = 1;</code>
     */
    HSM_CONTROLLED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WA_PROVIDED = 0;</code>
     */
    public static final int WA_PROVIDED_VALUE = 0;
    /**
     * <code>HSM_CONTROLLED = 1;</code>
     */
    public static final int HSM_CONTROLLED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Key_Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Key_Type forNumber(int value) {
      switch (value) {
        case 0: return WA_PROVIDED;
        case 1: return HSM_CONTROLLED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Key_Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Key_Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Key_Type>() {
            public Key_Type findValueByNumber(int number) {
              return Key_Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return whatsappbackupreader.protos.KeyType.getDescriptor().getEnumTypes().get(0);
    }

    private static final Key_Type[] VALUES = values();

    public static Key_Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Key_Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Key_Type)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016key_type.proto*/\n\010Key_Type\022\017\n\013WA_PROVI" +
      "DED\020\000\022\022\n\016HSM_CONTROLLED\020\001B\035\n\033whatsappbac" +
      "kupreader.protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
